---
/detect_lane:
  ros__parameters:
    detect:
      lane:
        white:
          hue_h: 95
          hue_l: 5
          lightness_h: 255
          lightness_l: 188
          saturation_h: 53
          saturation_l: 0
        yellow:
          hue_h: 93
          hue_l: 16
          lightness_h: 255
          lightness_l: 64
          saturation_h: 255
          saturation_l: 49
